import Generic from "../pages/Generic/Index.jsx";
import { ReactComponent as buyurtmalar } from "../assets/icons/buyurtmalar.svg";
export const sidebar = [
  {
    id: 1,
    title: "Buyurtmalar",
    component: Generic,
    icon: buyurtmalar,
    pathname: "/Buyurtmalar",
    child: [],
    hidden: false,
  },
  {
    id: 2,
    title: "MaHsulotlar",
    component: Generic,
    icon: buyurtmalar,
    pathname: "/MaHsulotlar",
    child: [],
    hidden: false,
  },
  {
    id: 3,
    title: "Kategoriyalar",
    component: Generic,
    icon: buyurtmalar,
    pathname: "/Kategoriyalar",
    child: [],
    hidden: false,
  },
  {
    id: 4,
    title: "  ",
    component: Generic,
    icon: buyurtmalar,
    pathname: "/Filiallar",
    child: [],
    hidden: false,
  },
  {
    id: 5,
    title: "Hisobot",
    component: Generic,
    icon: buyurtmalar,
    pathname: "/Hisobot",
    child: [],
    hidden: false,
  },
  {
    id: 6,
    title: "Mijozlar",
    component: Generic,
    icon: buyurtmalar,
    pathname: "/Mijozlar",
    child: [],
    hidden: false,
  },
  {
    id: 7,
    title: "Hodimlar",
    component: Generic,
    icon: buyurtmalar,
    pathname: "/Hodimlar",
    child: [],
    hidden: false,
  },
];
